### PR TITLE
Removed LoadUserItem method

### PR DESCRIPTION
**Pull request by tomasz-buchta**
Removed LoadUserItem method as it had sense only if the records in table USER_VALS existed.

### CODE REVIEW

**Comment by tomasz-buchta** [comment]
Naprawia #1

**Comment by przezor** [comment]
@jonaszmclaren Mógłbyś zrobić review?

**Comment by jonaszmclaren** [comment]
@przezor Sure, but I don't know if I will manage today, if not, I'll do it tomorrow:)

**Comment by jonaszmclaren** [comment]
It looks properly done.

**Comment by przezor** [comment]
Please merge pull request @jonaszmclaren

**Comment by jonaszmclaren** [comment]
I think I do not have write access to do it.

**Pull request merged**
