### PR TITLE
Exception logger

### PR DESCRIPTION
**Pull request by tomasz-buchta**
#4 In my opinion adding exception logger as separate pr would make our code review faster and easier.

### CODE REVIEW

**Comment by gabr** [comment]
Will it work for GUI version to?

**Comment by tomasz-buchta** [comment]
Yes, It will append logs to Logfile.txt in no matter if you run the program with GUI or just cmd

**Comment by kkoscielniak** [comment]
I approve the solution. If @gabr has no other questions, I'd like to merge and close the issue.

**Comment by gabr** [comment]
I'm ok with this solution.

**Pull request merged**
